// Code generated by entc, DO NOT EDIT.

package biouser

const (
	// Label holds the string label denoting the biouser type in the database.
	Label = "bio_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the biouser in the database.
	Table = "bio_users"
)

// Columns holds all SQL columns for biouser fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
)
