// Code generated by entc, DO NOT EDIT.

package enttiktokuser

const (
	// Label holds the string label denoting the enttiktokuser type in the database.
	Label = "ent_tik_tok_user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// Table holds the table name of the enttiktokuser in the database.
	Table = "ent_tik_tok_users"
)

// Columns holds all SQL columns for enttiktokuser fields.
var Columns = []string{
	FieldID,
	FieldName,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultName holds the default value on creation for the "name" field.
	DefaultName string
)
