// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/biouser"
	"fmt"
	"strings"

	"entgo.io/ent/dialect/sql"
)

// BioUser is the model entity for the BioUser schema.
type BioUser struct {
	config `json:"-"`
	// ID of the ent.
	ID int `json:"id,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
}

// scanValues returns the types for scanning values from sql.Rows.
func (*BioUser) scanValues(columns []string) ([]interface{}, error) {
	values := make([]interface{}, len(columns))
	for i := range columns {
		switch columns[i] {
		case biouser.FieldID:
			values[i] = new(sql.NullInt64)
		case biouser.FieldName:
			values[i] = new(sql.NullString)
		default:
			return nil, fmt.Errorf("unexpected column %q for type BioUser", columns[i])
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the BioUser fields.
func (bu *BioUser) assignValues(columns []string, values []interface{}) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case biouser.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			bu.ID = int(value.Int64)
		case biouser.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				bu.Name = value.String
			}
		}
	}
	return nil
}

// Update returns a builder for updating this BioUser.
// Note that you need to call BioUser.Unwrap() before calling this method if this BioUser
// was returned from a transaction, and the transaction was committed or rolled back.
func (bu *BioUser) Update() *BioUserUpdateOne {
	return (&BioUserClient{config: bu.config}).UpdateOne(bu)
}

// Unwrap unwraps the BioUser entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (bu *BioUser) Unwrap() *BioUser {
	tx, ok := bu.config.driver.(*txDriver)
	if !ok {
		panic("ent: BioUser is not a transactional entity")
	}
	bu.config.driver = tx.drv
	return bu
}

// String implements the fmt.Stringer.
func (bu *BioUser) String() string {
	var builder strings.Builder
	builder.WriteString("BioUser(")
	builder.WriteString(fmt.Sprintf("id=%v", bu.ID))
	builder.WriteString(", name=")
	builder.WriteString(bu.Name)
	builder.WriteByte(')')
	return builder.String()
}

// BioUsers is a parsable slice of BioUser.
type BioUsers []*BioUser

func (bu BioUsers) config(cfg config) {
	for _i := range bu {
		bu[_i].config = cfg
	}
}
