// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/enttiktokuser"
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntTikTokUserCreate is the builder for creating a EntTikTokUser entity.
type EntTikTokUserCreate struct {
	config
	mutation *EntTikTokUserMutation
	hooks    []Hook
}

// SetName sets the "name" field.
func (ettuc *EntTikTokUserCreate) SetName(s string) *EntTikTokUserCreate {
	ettuc.mutation.SetName(s)
	return ettuc
}

// SetNillableName sets the "name" field if the given value is not nil.
func (ettuc *EntTikTokUserCreate) SetNillableName(s *string) *EntTikTokUserCreate {
	if s != nil {
		ettuc.SetName(*s)
	}
	return ettuc
}

// Mutation returns the EntTikTokUserMutation object of the builder.
func (ettuc *EntTikTokUserCreate) Mutation() *EntTikTokUserMutation {
	return ettuc.mutation
}

// Save creates the EntTikTokUser in the database.
func (ettuc *EntTikTokUserCreate) Save(ctx context.Context) (*EntTikTokUser, error) {
	var (
		err  error
		node *EntTikTokUser
	)
	ettuc.defaults()
	if len(ettuc.hooks) == 0 {
		if err = ettuc.check(); err != nil {
			return nil, err
		}
		node, err = ettuc.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntTikTokUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = ettuc.check(); err != nil {
				return nil, err
			}
			ettuc.mutation = mutation
			if node, err = ettuc.sqlSave(ctx); err != nil {
				return nil, err
			}
			mutation.id = &node.ID
			mutation.done = true
			return node, err
		})
		for i := len(ettuc.hooks) - 1; i >= 0; i-- {
			if ettuc.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ettuc.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ettuc.mutation); err != nil {
			return nil, err
		}
	}
	return node, err
}

// SaveX calls Save and panics if Save returns an error.
func (ettuc *EntTikTokUserCreate) SaveX(ctx context.Context) *EntTikTokUser {
	v, err := ettuc.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ettuc *EntTikTokUserCreate) Exec(ctx context.Context) error {
	_, err := ettuc.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ettuc *EntTikTokUserCreate) ExecX(ctx context.Context) {
	if err := ettuc.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ettuc *EntTikTokUserCreate) defaults() {
	if _, ok := ettuc.mutation.Name(); !ok {
		v := enttiktokuser.DefaultName
		ettuc.mutation.SetName(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ettuc *EntTikTokUserCreate) check() error {
	if _, ok := ettuc.mutation.Name(); !ok {
		return &ValidationError{Name: "name", err: errors.New(`ent: missing required field "name"`)}
	}
	return nil
}

func (ettuc *EntTikTokUserCreate) sqlSave(ctx context.Context) (*EntTikTokUser, error) {
	_node, _spec := ettuc.createSpec()
	if err := sqlgraph.CreateNode(ctx, ettuc.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{err.Error(), err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int(id)
	return _node, nil
}

func (ettuc *EntTikTokUserCreate) createSpec() (*EntTikTokUser, *sqlgraph.CreateSpec) {
	var (
		_node = &EntTikTokUser{config: ettuc.config}
		_spec = &sqlgraph.CreateSpec{
			Table: enttiktokuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: enttiktokuser.FieldID,
			},
		}
	)
	if value, ok := ettuc.mutation.Name(); ok {
		_spec.Fields = append(_spec.Fields, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: enttiktokuser.FieldName,
		})
		_node.Name = value
	}
	return _node, _spec
}

// EntTikTokUserCreateBulk is the builder for creating many EntTikTokUser entities in bulk.
type EntTikTokUserCreateBulk struct {
	config
	builders []*EntTikTokUserCreate
}

// Save creates the EntTikTokUser entities in the database.
func (ettucb *EntTikTokUserCreateBulk) Save(ctx context.Context) ([]*EntTikTokUser, error) {
	specs := make([]*sqlgraph.CreateSpec, len(ettucb.builders))
	nodes := make([]*EntTikTokUser, len(ettucb.builders))
	mutators := make([]Mutator, len(ettucb.builders))
	for i := range ettucb.builders {
		func(i int, root context.Context) {
			builder := ettucb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*EntTikTokUserMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				nodes[i], specs[i] = builder.createSpec()
				var err error
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, ettucb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, ettucb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{err.Error(), err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int(id)
				}
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, ettucb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (ettucb *EntTikTokUserCreateBulk) SaveX(ctx context.Context) []*EntTikTokUser {
	v, err := ettucb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ettucb *EntTikTokUserCreateBulk) Exec(ctx context.Context) error {
	_, err := ettucb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ettucb *EntTikTokUserCreateBulk) ExecX(ctx context.Context) {
	if err := ettucb.Exec(ctx); err != nil {
		panic(err)
	}
}
