// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/enttiktokuser"
	"back/ent/predicate"
	"context"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntTikTokUserDelete is the builder for deleting a EntTikTokUser entity.
type EntTikTokUserDelete struct {
	config
	hooks    []Hook
	mutation *EntTikTokUserMutation
}

// Where appends a list predicates to the EntTikTokUserDelete builder.
func (ettud *EntTikTokUserDelete) Where(ps ...predicate.EntTikTokUser) *EntTikTokUserDelete {
	ettud.mutation.Where(ps...)
	return ettud
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (ettud *EntTikTokUserDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(ettud.hooks) == 0 {
		affected, err = ettud.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EntTikTokUserMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ettud.mutation = mutation
			affected, err = ettud.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ettud.hooks) - 1; i >= 0; i-- {
			if ettud.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ettud.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ettud.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (ettud *EntTikTokUserDelete) ExecX(ctx context.Context) int {
	n, err := ettud.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (ettud *EntTikTokUserDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: enttiktokuser.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: enttiktokuser.FieldID,
			},
		},
	}
	if ps := ettud.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return sqlgraph.DeleteNodes(ctx, ettud.driver, _spec)
}

// EntTikTokUserDeleteOne is the builder for deleting a single EntTikTokUser entity.
type EntTikTokUserDeleteOne struct {
	ettud *EntTikTokUserDelete
}

// Exec executes the deletion query.
func (ettudo *EntTikTokUserDeleteOne) Exec(ctx context.Context) error {
	n, err := ettudo.ettud.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{enttiktokuser.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (ettudo *EntTikTokUserDeleteOne) ExecX(ctx context.Context) {
	ettudo.ettud.ExecX(ctx)
}
