// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/enttiktokuser"
	"back/ent/predicate"
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// EntTikTokUserQuery is the builder for querying EntTikTokUser entities.
type EntTikTokUserQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.EntTikTokUser
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the EntTikTokUserQuery builder.
func (ettuq *EntTikTokUserQuery) Where(ps ...predicate.EntTikTokUser) *EntTikTokUserQuery {
	ettuq.predicates = append(ettuq.predicates, ps...)
	return ettuq
}

// Limit adds a limit step to the query.
func (ettuq *EntTikTokUserQuery) Limit(limit int) *EntTikTokUserQuery {
	ettuq.limit = &limit
	return ettuq
}

// Offset adds an offset step to the query.
func (ettuq *EntTikTokUserQuery) Offset(offset int) *EntTikTokUserQuery {
	ettuq.offset = &offset
	return ettuq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (ettuq *EntTikTokUserQuery) Unique(unique bool) *EntTikTokUserQuery {
	ettuq.unique = &unique
	return ettuq
}

// Order adds an order step to the query.
func (ettuq *EntTikTokUserQuery) Order(o ...OrderFunc) *EntTikTokUserQuery {
	ettuq.order = append(ettuq.order, o...)
	return ettuq
}

// First returns the first EntTikTokUser entity from the query.
// Returns a *NotFoundError when no EntTikTokUser was found.
func (ettuq *EntTikTokUserQuery) First(ctx context.Context) (*EntTikTokUser, error) {
	nodes, err := ettuq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{enttiktokuser.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) FirstX(ctx context.Context) *EntTikTokUser {
	node, err := ettuq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first EntTikTokUser ID from the query.
// Returns a *NotFoundError when no EntTikTokUser ID was found.
func (ettuq *EntTikTokUserQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ettuq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{enttiktokuser.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) FirstIDX(ctx context.Context) int {
	id, err := ettuq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single EntTikTokUser entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when exactly one EntTikTokUser entity is not found.
// Returns a *NotFoundError when no EntTikTokUser entities are found.
func (ettuq *EntTikTokUserQuery) Only(ctx context.Context) (*EntTikTokUser, error) {
	nodes, err := ettuq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{enttiktokuser.Label}
	default:
		return nil, &NotSingularError{enttiktokuser.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) OnlyX(ctx context.Context) *EntTikTokUser {
	node, err := ettuq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only EntTikTokUser ID in the query.
// Returns a *NotSingularError when exactly one EntTikTokUser ID is not found.
// Returns a *NotFoundError when no entities are found.
func (ettuq *EntTikTokUserQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = ettuq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = &NotSingularError{enttiktokuser.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) OnlyIDX(ctx context.Context) int {
	id, err := ettuq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of EntTikTokUsers.
func (ettuq *EntTikTokUserQuery) All(ctx context.Context) ([]*EntTikTokUser, error) {
	if err := ettuq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return ettuq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) AllX(ctx context.Context) []*EntTikTokUser {
	nodes, err := ettuq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of EntTikTokUser IDs.
func (ettuq *EntTikTokUserQuery) IDs(ctx context.Context) ([]int, error) {
	var ids []int
	if err := ettuq.Select(enttiktokuser.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) IDsX(ctx context.Context) []int {
	ids, err := ettuq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (ettuq *EntTikTokUserQuery) Count(ctx context.Context) (int, error) {
	if err := ettuq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return ettuq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) CountX(ctx context.Context) int {
	count, err := ettuq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (ettuq *EntTikTokUserQuery) Exist(ctx context.Context) (bool, error) {
	if err := ettuq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return ettuq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (ettuq *EntTikTokUserQuery) ExistX(ctx context.Context) bool {
	exist, err := ettuq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the EntTikTokUserQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (ettuq *EntTikTokUserQuery) Clone() *EntTikTokUserQuery {
	if ettuq == nil {
		return nil
	}
	return &EntTikTokUserQuery{
		config:     ettuq.config,
		limit:      ettuq.limit,
		offset:     ettuq.offset,
		order:      append([]OrderFunc{}, ettuq.order...),
		predicates: append([]predicate.EntTikTokUser{}, ettuq.predicates...),
		// clone intermediate query.
		sql:  ettuq.sql.Clone(),
		path: ettuq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.EntTikTokUser.Query().
//		GroupBy(enttiktokuser.FieldName).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (ettuq *EntTikTokUserQuery) GroupBy(field string, fields ...string) *EntTikTokUserGroupBy {
	group := &EntTikTokUserGroupBy{config: ettuq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := ettuq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return ettuq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Name string `json:"name,omitempty"`
//	}
//
//	client.EntTikTokUser.Query().
//		Select(enttiktokuser.FieldName).
//		Scan(ctx, &v)
//
func (ettuq *EntTikTokUserQuery) Select(fields ...string) *EntTikTokUserSelect {
	ettuq.fields = append(ettuq.fields, fields...)
	return &EntTikTokUserSelect{EntTikTokUserQuery: ettuq}
}

func (ettuq *EntTikTokUserQuery) prepareQuery(ctx context.Context) error {
	for _, f := range ettuq.fields {
		if !enttiktokuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if ettuq.path != nil {
		prev, err := ettuq.path(ctx)
		if err != nil {
			return err
		}
		ettuq.sql = prev
	}
	return nil
}

func (ettuq *EntTikTokUserQuery) sqlAll(ctx context.Context) ([]*EntTikTokUser, error) {
	var (
		nodes = []*EntTikTokUser{}
		_spec = ettuq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &EntTikTokUser{config: ettuq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, ettuq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (ettuq *EntTikTokUserQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := ettuq.querySpec()
	return sqlgraph.CountNodes(ctx, ettuq.driver, _spec)
}

func (ettuq *EntTikTokUserQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := ettuq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (ettuq *EntTikTokUserQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   enttiktokuser.Table,
			Columns: enttiktokuser.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: enttiktokuser.FieldID,
			},
		},
		From:   ettuq.sql,
		Unique: true,
	}
	if unique := ettuq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := ettuq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, enttiktokuser.FieldID)
		for i := range fields {
			if fields[i] != enttiktokuser.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := ettuq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := ettuq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := ettuq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := ettuq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (ettuq *EntTikTokUserQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(ettuq.driver.Dialect())
	t1 := builder.Table(enttiktokuser.Table)
	columns := ettuq.fields
	if len(columns) == 0 {
		columns = enttiktokuser.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if ettuq.sql != nil {
		selector = ettuq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	for _, p := range ettuq.predicates {
		p(selector)
	}
	for _, p := range ettuq.order {
		p(selector)
	}
	if offset := ettuq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := ettuq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// EntTikTokUserGroupBy is the group-by builder for EntTikTokUser entities.
type EntTikTokUserGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (ettugb *EntTikTokUserGroupBy) Aggregate(fns ...AggregateFunc) *EntTikTokUserGroupBy {
	ettugb.fns = append(ettugb.fns, fns...)
	return ettugb
}

// Scan applies the group-by query and scans the result into the given value.
func (ettugb *EntTikTokUserGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := ettugb.path(ctx)
	if err != nil {
		return err
	}
	ettugb.sql = query
	return ettugb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := ettugb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(ettugb.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := ettugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) StringsX(ctx context.Context) []string {
	v, err := ettugb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ettugb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) StringX(ctx context.Context) string {
	v, err := ettugb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(ettugb.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := ettugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) IntsX(ctx context.Context) []int {
	v, err := ettugb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ettugb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) IntX(ctx context.Context) int {
	v, err := ettugb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(ettugb.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := ettugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := ettugb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ettugb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) Float64X(ctx context.Context) float64 {
	v, err := ettugb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(ettugb.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := ettugb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := ettugb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (ettugb *EntTikTokUserGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ettugb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ettugb *EntTikTokUserGroupBy) BoolX(ctx context.Context) bool {
	v, err := ettugb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ettugb *EntTikTokUserGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range ettugb.fields {
		if !enttiktokuser.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := ettugb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := ettugb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (ettugb *EntTikTokUserGroupBy) sqlQuery() *sql.Selector {
	selector := ettugb.sql.Select()
	aggregation := make([]string, 0, len(ettugb.fns))
	for _, fn := range ettugb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(ettugb.fields)+len(ettugb.fns))
		for _, f := range ettugb.fields {
			columns = append(columns, selector.C(f))
		}
		for _, c := range aggregation {
			columns = append(columns, c)
		}
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(ettugb.fields...)...)
}

// EntTikTokUserSelect is the builder for selecting fields of EntTikTokUser entities.
type EntTikTokUserSelect struct {
	*EntTikTokUserQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (ettus *EntTikTokUserSelect) Scan(ctx context.Context, v interface{}) error {
	if err := ettus.prepareQuery(ctx); err != nil {
		return err
	}
	ettus.sql = ettus.EntTikTokUserQuery.sqlQuery(ctx)
	return ettus.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) ScanX(ctx context.Context, v interface{}) {
	if err := ettus.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Strings(ctx context.Context) ([]string, error) {
	if len(ettus.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := ettus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) StringsX(ctx context.Context) []string {
	v, err := ettus.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = ettus.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) StringX(ctx context.Context) string {
	v, err := ettus.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Ints(ctx context.Context) ([]int, error) {
	if len(ettus.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := ettus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) IntsX(ctx context.Context) []int {
	v, err := ettus.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = ettus.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) IntX(ctx context.Context) int {
	v, err := ettus.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(ettus.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := ettus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) Float64sX(ctx context.Context) []float64 {
	v, err := ettus.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = ettus.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) Float64X(ctx context.Context) float64 {
	v, err := ettus.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(ettus.fields) > 1 {
		return nil, errors.New("ent: EntTikTokUserSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := ettus.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) BoolsX(ctx context.Context) []bool {
	v, err := ettus.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (ettus *EntTikTokUserSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = ettus.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{enttiktokuser.Label}
	default:
		err = fmt.Errorf("ent: EntTikTokUserSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (ettus *EntTikTokUserSelect) BoolX(ctx context.Context) bool {
	v, err := ettus.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (ettus *EntTikTokUserSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := ettus.sql.Query()
	if err := ettus.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
