// Code generated by entc, DO NOT EDIT.

package ent

import (
	"back/ent/biouser"
	"back/ent/enttiktokuser"
	"back/ent/predicate"
	"context"
	"fmt"
	"sync"

	"entgo.io/ent"
)

const (
	// Operation types.
	OpCreate    = ent.OpCreate
	OpDelete    = ent.OpDelete
	OpDeleteOne = ent.OpDeleteOne
	OpUpdate    = ent.OpUpdate
	OpUpdateOne = ent.OpUpdateOne

	// Node types.
	TypeBioUser       = "BioUser"
	TypeEntTikTokUser = "EntTikTokUser"
)

// BioUserMutation represents an operation that mutates the BioUser nodes in the graph.
type BioUserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*BioUser, error)
	predicates    []predicate.BioUser
}

var _ ent.Mutation = (*BioUserMutation)(nil)

// biouserOption allows management of the mutation configuration using functional options.
type biouserOption func(*BioUserMutation)

// newBioUserMutation creates new mutation for the BioUser entity.
func newBioUserMutation(c config, op Op, opts ...biouserOption) *BioUserMutation {
	m := &BioUserMutation{
		config:        c,
		op:            op,
		typ:           TypeBioUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withBioUserID sets the ID field of the mutation.
func withBioUserID(id int) biouserOption {
	return func(m *BioUserMutation) {
		var (
			err   error
			once  sync.Once
			value *BioUser
		)
		m.oldValue = func(ctx context.Context) (*BioUser, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().BioUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withBioUser sets the old BioUser of the mutation.
func withBioUser(node *BioUser) biouserOption {
	return func(m *BioUserMutation) {
		m.oldValue = func(context.Context) (*BioUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m BioUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m BioUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *BioUserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the "name" field.
func (m *BioUserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *BioUserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the BioUser entity.
// If the BioUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *BioUserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *BioUserMutation) ResetName() {
	m.name = nil
}

// Where appends a list predicates to the BioUserMutation builder.
func (m *BioUserMutation) Where(ps ...predicate.BioUser) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *BioUserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (BioUser).
func (m *BioUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *BioUserMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, biouser.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *BioUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case biouser.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *BioUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case biouser.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown BioUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BioUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case biouser.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown BioUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *BioUserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *BioUserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *BioUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown BioUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *BioUserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *BioUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *BioUserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown BioUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *BioUserMutation) ResetField(name string) error {
	switch name {
	case biouser.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown BioUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *BioUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *BioUserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *BioUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *BioUserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *BioUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *BioUserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *BioUserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown BioUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *BioUserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown BioUser edge %s", name)
}

// EntTikTokUserMutation represents an operation that mutates the EntTikTokUser nodes in the graph.
type EntTikTokUserMutation struct {
	config
	op            Op
	typ           string
	id            *int
	name          *string
	clearedFields map[string]struct{}
	done          bool
	oldValue      func(context.Context) (*EntTikTokUser, error)
	predicates    []predicate.EntTikTokUser
}

var _ ent.Mutation = (*EntTikTokUserMutation)(nil)

// enttiktokuserOption allows management of the mutation configuration using functional options.
type enttiktokuserOption func(*EntTikTokUserMutation)

// newEntTikTokUserMutation creates new mutation for the EntTikTokUser entity.
func newEntTikTokUserMutation(c config, op Op, opts ...enttiktokuserOption) *EntTikTokUserMutation {
	m := &EntTikTokUserMutation{
		config:        c,
		op:            op,
		typ:           TypeEntTikTokUser,
		clearedFields: make(map[string]struct{}),
	}
	for _, opt := range opts {
		opt(m)
	}
	return m
}

// withEntTikTokUserID sets the ID field of the mutation.
func withEntTikTokUserID(id int) enttiktokuserOption {
	return func(m *EntTikTokUserMutation) {
		var (
			err   error
			once  sync.Once
			value *EntTikTokUser
		)
		m.oldValue = func(ctx context.Context) (*EntTikTokUser, error) {
			once.Do(func() {
				if m.done {
					err = fmt.Errorf("querying old values post mutation is not allowed")
				} else {
					value, err = m.Client().EntTikTokUser.Get(ctx, id)
				}
			})
			return value, err
		}
		m.id = &id
	}
}

// withEntTikTokUser sets the old EntTikTokUser of the mutation.
func withEntTikTokUser(node *EntTikTokUser) enttiktokuserOption {
	return func(m *EntTikTokUserMutation) {
		m.oldValue = func(context.Context) (*EntTikTokUser, error) {
			return node, nil
		}
		m.id = &node.ID
	}
}

// Client returns a new `ent.Client` from the mutation. If the mutation was
// executed in a transaction (ent.Tx), a transactional client is returned.
func (m EntTikTokUserMutation) Client() *Client {
	client := &Client{config: m.config}
	client.init()
	return client
}

// Tx returns an `ent.Tx` for mutations that were executed in transactions;
// it returns an error otherwise.
func (m EntTikTokUserMutation) Tx() (*Tx, error) {
	if _, ok := m.driver.(*txDriver); !ok {
		return nil, fmt.Errorf("ent: mutation is not running in a transaction")
	}
	tx := &Tx{config: m.config}
	tx.init()
	return tx, nil
}

// ID returns the ID value in the mutation. Note that the ID is only available
// if it was provided to the builder or after it was returned from the database.
func (m *EntTikTokUserMutation) ID() (id int, exists bool) {
	if m.id == nil {
		return
	}
	return *m.id, true
}

// SetName sets the "name" field.
func (m *EntTikTokUserMutation) SetName(s string) {
	m.name = &s
}

// Name returns the value of the "name" field in the mutation.
func (m *EntTikTokUserMutation) Name() (r string, exists bool) {
	v := m.name
	if v == nil {
		return
	}
	return *v, true
}

// OldName returns the old "name" field's value of the EntTikTokUser entity.
// If the EntTikTokUser object wasn't provided to the builder, the object is fetched from the database.
// An error is returned if the mutation operation is not UpdateOne, or the database query fails.
func (m *EntTikTokUserMutation) OldName(ctx context.Context) (v string, err error) {
	if !m.op.Is(OpUpdateOne) {
		return v, fmt.Errorf("OldName is only allowed on UpdateOne operations")
	}
	if m.id == nil || m.oldValue == nil {
		return v, fmt.Errorf("OldName requires an ID field in the mutation")
	}
	oldValue, err := m.oldValue(ctx)
	if err != nil {
		return v, fmt.Errorf("querying old value for OldName: %w", err)
	}
	return oldValue.Name, nil
}

// ResetName resets all changes to the "name" field.
func (m *EntTikTokUserMutation) ResetName() {
	m.name = nil
}

// Where appends a list predicates to the EntTikTokUserMutation builder.
func (m *EntTikTokUserMutation) Where(ps ...predicate.EntTikTokUser) {
	m.predicates = append(m.predicates, ps...)
}

// Op returns the operation name.
func (m *EntTikTokUserMutation) Op() Op {
	return m.op
}

// Type returns the node type of this mutation (EntTikTokUser).
func (m *EntTikTokUserMutation) Type() string {
	return m.typ
}

// Fields returns all fields that were changed during this mutation. Note that in
// order to get all numeric fields that were incremented/decremented, call
// AddedFields().
func (m *EntTikTokUserMutation) Fields() []string {
	fields := make([]string, 0, 1)
	if m.name != nil {
		fields = append(fields, enttiktokuser.FieldName)
	}
	return fields
}

// Field returns the value of a field with the given name. The second boolean
// return value indicates that this field was not set, or was not defined in the
// schema.
func (m *EntTikTokUserMutation) Field(name string) (ent.Value, bool) {
	switch name {
	case enttiktokuser.FieldName:
		return m.Name()
	}
	return nil, false
}

// OldField returns the old value of the field from the database. An error is
// returned if the mutation operation is not UpdateOne, or the query to the
// database failed.
func (m *EntTikTokUserMutation) OldField(ctx context.Context, name string) (ent.Value, error) {
	switch name {
	case enttiktokuser.FieldName:
		return m.OldName(ctx)
	}
	return nil, fmt.Errorf("unknown EntTikTokUser field %s", name)
}

// SetField sets the value of a field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EntTikTokUserMutation) SetField(name string, value ent.Value) error {
	switch name {
	case enttiktokuser.FieldName:
		v, ok := value.(string)
		if !ok {
			return fmt.Errorf("unexpected type %T for field %s", value, name)
		}
		m.SetName(v)
		return nil
	}
	return fmt.Errorf("unknown EntTikTokUser field %s", name)
}

// AddedFields returns all numeric fields that were incremented/decremented during
// this mutation.
func (m *EntTikTokUserMutation) AddedFields() []string {
	return nil
}

// AddedField returns the numeric value that was incremented/decremented on a field
// with the given name. The second boolean return value indicates that this field
// was not set, or was not defined in the schema.
func (m *EntTikTokUserMutation) AddedField(name string) (ent.Value, bool) {
	return nil, false
}

// AddField adds the value to the field with the given name. It returns an error if
// the field is not defined in the schema, or if the type mismatched the field
// type.
func (m *EntTikTokUserMutation) AddField(name string, value ent.Value) error {
	switch name {
	}
	return fmt.Errorf("unknown EntTikTokUser numeric field %s", name)
}

// ClearedFields returns all nullable fields that were cleared during this
// mutation.
func (m *EntTikTokUserMutation) ClearedFields() []string {
	return nil
}

// FieldCleared returns a boolean indicating if a field with the given name was
// cleared in this mutation.
func (m *EntTikTokUserMutation) FieldCleared(name string) bool {
	_, ok := m.clearedFields[name]
	return ok
}

// ClearField clears the value of the field with the given name. It returns an
// error if the field is not defined in the schema.
func (m *EntTikTokUserMutation) ClearField(name string) error {
	return fmt.Errorf("unknown EntTikTokUser nullable field %s", name)
}

// ResetField resets all changes in the mutation for the field with the given name.
// It returns an error if the field is not defined in the schema.
func (m *EntTikTokUserMutation) ResetField(name string) error {
	switch name {
	case enttiktokuser.FieldName:
		m.ResetName()
		return nil
	}
	return fmt.Errorf("unknown EntTikTokUser field %s", name)
}

// AddedEdges returns all edge names that were set/added in this mutation.
func (m *EntTikTokUserMutation) AddedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// AddedIDs returns all IDs (to other nodes) that were added for the given edge
// name in this mutation.
func (m *EntTikTokUserMutation) AddedIDs(name string) []ent.Value {
	return nil
}

// RemovedEdges returns all edge names that were removed in this mutation.
func (m *EntTikTokUserMutation) RemovedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// RemovedIDs returns all IDs (to other nodes) that were removed for the edge with
// the given name in this mutation.
func (m *EntTikTokUserMutation) RemovedIDs(name string) []ent.Value {
	return nil
}

// ClearedEdges returns all edge names that were cleared in this mutation.
func (m *EntTikTokUserMutation) ClearedEdges() []string {
	edges := make([]string, 0, 0)
	return edges
}

// EdgeCleared returns a boolean which indicates if the edge with the given name
// was cleared in this mutation.
func (m *EntTikTokUserMutation) EdgeCleared(name string) bool {
	return false
}

// ClearEdge clears the value of the edge with the given name. It returns an error
// if that edge is not defined in the schema.
func (m *EntTikTokUserMutation) ClearEdge(name string) error {
	return fmt.Errorf("unknown EntTikTokUser unique edge %s", name)
}

// ResetEdge resets all changes to the edge with the given name in this mutation.
// It returns an error if the edge is not defined in the schema.
func (m *EntTikTokUserMutation) ResetEdge(name string) error {
	return fmt.Errorf("unknown EntTikTokUser edge %s", name)
}
