// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BioUsersColumns holds the columns for the "bio_users" table.
	BioUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "name", Type: field.TypeString, Default: "unknown"},
	}
	// BioUsersTable holds the schema information for the "bio_users" table.
	BioUsersTable = &schema.Table{
		Name:       "bio_users",
		Columns:    BioUsersColumns,
		PrimaryKey: []*schema.Column{BioUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BioUsersTable,
	}
)

func init() {
}
